### ISSUE TITLE
How to add title for every step?

### ISSUE THREAD

**Issue by openhappyya** [adi-works/vue-stepper#50]
![image](https://user-images.githubusercontent.com/68777460/227721217-cf08beab-fcfd-4147-b65b-bece234d3704.png)
 there is no tip in the using docx.

**Comment by Telexine** [comment]
Traveler, this is my quick css workaround 
 
```
::v-deep .v-stepper-root > :first-child::after {
  content: 'Submit Form';
  display: block;
  padding: 5px;
}

::v-deep .v-stepper-root > :nth-child(2)::after {
  content: 'OTP';
  display: block;
  padding: 5px;
}
::v-deep .v-stepper-root > :nth-child(3)::after {
  content: 'Result';
  display: block;
  padding: 5px;
}
```

**Comment by adi518** [comment]
The docs are missing that piece of information, sorry about that.

You have to use the `step<n>` slots, see this example from the docs source: https://github.com/adi518/vue-stepper/blob/master/docs/src/containers/Docs.vue#L32
